In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
hello = tf.constant("hello")

In [ ]:
print(hello)

tf.Tensor(b'hello', shape=(), dtype=string)


In [ ]:
tensor_1d = np.array([1.3, 1.5, 3.5, 6.2])
print(tensor_1d)

[1.3 1.5 3.5 6.2]


In [ ]:
print(tensor_1d[3])

6.2


In [ ]:
tensor_2d = np.array([(1.3, 1.5, 3.5, 6.2),(5.3, 1.9, 7.5, 6.0), (4.5, 2.4, 3.0, 5.4), (2.3, 6.8, 1.4, 6.8)])
print(tensor_2d)

[[1.3 1.5 3.5 6.2]
 [5.3 1.9 7.5 6. ]
 [4.5 2.4 3.  5.4]
 [2.3 6.8 1.4 6.8]]


In [ ]:
print(tensor_2d[3][1])

6.8


In [ ]:
matrix1 = np.array([(3, 5, 2),(1, 6, 3),(2, 7, 5)])
matrix2 = np.array([(2, 4, 1),(1, 2, 3),(3, 4, 3)])
print(matrix1)
print(matrix2)

[[3 5 2]
 [1 6 3]
 [2 7 5]]
[[2 4 1]
 [1 2 3]
 [3 4 3]]


In [ ]:
sum = tf.add(matrix1, matrix2)
print(sum)

tf.Tensor(
[[ 5  9  3]
 [ 2  8  6]
 [ 5 11  8]], shape=(3, 3), dtype=int64)


In [ ]:
subtract = tf.subtract(matrix1, matrix2)
print(subtract)

tf.Tensor(
[[ 1  1  1]
 [ 0  4  0]
 [-1  3  2]], shape=(3, 3), dtype=int64)


In [ ]:
product = tf.matmul(matrix1, matrix2)
print(product)

tf.Tensor(
[[17 30 24]
 [17 28 28]
 [26 42 38]], shape=(3, 3), dtype=int64)
